
require "prototypes.Vanilla_Changes.Functions"

Damage = {
	Small_Biter = Biter_Melee_Attack_Healthy(5),
	Small_Biter_Mk2 = Biter_Melee_Attack_Infected(8,5),
	Small_Biter_Mk3 = Biter_Melee_Attack_Mutated(10,5),
	Medium_Biter = Biter_Melee_Attack_Healthy(15),
	Medium_Biter_Mk2 = Biter_Melee_Attack_Infected(20,10),
	Medium_Biter_Mk3 = Biter_Melee_Attack_Mutated(20,10),
	Big_Biter = Biter_Melee_Attack_Healthy(40),
	Big_Biter_Mk2 = Biter_Melee_Attack_Infected(45,20),
	Big_Biter_Mk3 = Biter_Melee_Attack_Mutated(50,20),
	Behemoth_Biter = Biter_Melee_Attack_Healthy(100)
	}
	
	
Health = {
	Small_Biter = 15,
	Small_Biter_Mk2 = 30,
	Small_Biter_Mk3 = 45,
	Medium_Biter = 75,
	Medium_Biter_Mk2 = 150,
	Medium_Biter_Mk3 = 225,
	Big_Biter = 375,
	Big_Biter_Mk2 = 750,
	Big_Biter_Mk3 = 1125,
	Behemoth_Biter = 5000,
	Small_Spitter = 10,
	Small_Spitter_Mk2 = 20,
	Small_Spitter_Mk3 = 30,
	Medium_Spitter = 50,
	Medium_Spitter_Mk2 = 100,
	Medium_Spitter_Mk3 = 150,
	Big_Spitter = 200,
	Big_Spitter_Mk2 = 450,
	Big_Spitter_Mk3 = 700,
	Behemoth_Spitter = 2000
	}



Resistances = {
	Small_Biter = {
	  {type = "fire", decrease = 0, percent = -45},
      {type = "physical", decrease = 1, percent = 5},
      {type = "impact", decrease = 1, percent = 0},
      {type = "explosion", decrease = 1, percent = 0},
      {type = "acid", decrease = 1, percent = 0},
      {type = "poison", decrease = 0, percent = 0},
      {type = "laser", decrease = 0, percent = 0}},
	Small_Biter_Mk2 = {
	  {type = "fire", decrease = 0, percent = -45},
      {type = "physical", decrease = 2, percent = 5},
      {type = "impact", decrease = 2, percent = 0},
      {type = "explosion", decrease = 2, percent = 0},
      {type = "acid", decrease = 2, percent = 0},
      {type = "poison", decrease = 0, percent = 0},
      {type = "laser", decrease = 0, percent = 0}},
	Small_Biter_Mk3 = {
	  {type = "fire", decrease = 0, percent = -40},
      {type = "physical", decrease = 3, percent = 5},
      {type = "impact", decrease = 3, percent = 0},
      {type = "explosion", decrease = 3, percent = 0},
      {type = "acid", decrease = 3, percent = 0},
      {type = "poison", decrease = 0, percent = 0},
      {type = "laser", decrease = 0, percent = 0}},
	Medium_Biter = {
	  {type = "fire", decrease = 0, percent = -35},
      {type = "physical", decrease = 2, percent = 5},
      {type = "impact", decrease = 5, percent = 0},
      {type = "explosion", decrease = 5, percent = 5},
      {type = "acid", decrease = 5, percent = 5},
      {type = "poison", decrease = 0, percent = 5},
      {type = "laser", decrease = 2, percent = 0}},
	Medium_Biter_Mk2 = {
	  {type = "fire", decrease = 0, percent = -35},
      {type = "physical", decrease = 3, percent = 0},
      {type = "impact", decrease = 6, percent = 5},
      {type = "explosion", decrease = 6, percent = 5},
      {type = "acid", decrease = 6, percent = 5},
      {type = "poison", decrease = 0, percent = 5},
      {type = "laser", decrease = 3, percent = 5}},
	Medium_Biter_Mk3 = {
	  {type = "fire", decrease = 0, percent = -30},
      {type = "physical", decrease = 4, percent = 5},
      {type = "impact", decrease = 7, percent = 5},
      {type = "explosion", decrease = 7, percent = 5},
      {type = "acid", decrease = 7, percent = 5},
      {type = "poison", decrease = 0, percent = 5},
      {type = "laser", decrease = 4, percent = 5}},
	Big_Biter = {
	  {type = "fire", decrease = 0, percent = -25},
      {type = "physical", decrease = 8, percent = 15},
      {type = "impact", decrease = 10, percent = 10},
      {type = "explosion", decrease = 10, percent = 10},
      {type = "acid", decrease = 10, percent = 10},
      {type = "poison", decrease = 0, percent = 10},
      {type = "laser", decrease = 5, percent = 5}},
	Big_Biter_Mk2 = {
	  {type = "fire", decrease = 0, percent = -25},
      {type = "physical", decrease = 10, percent = 15},
      {type = "impact", decrease = 11, percent = 10},
      {type = "explosion", decrease = 11, percent = 10},
      {type = "acid", decrease = 11, percent = 10},
      {type = "poison", decrease = 0, percent = 10},
      {type = "laser", decrease = 5, percent = 10}},
	Big_Biter_Mk3 = {
	  {type = "fire", decrease = 0, percent = -25},
      {type = "physical", decrease = 12, percent = 15},
      {type = "impact", decrease = 10, percent = 10},
      {type = "explosion", decrease = 12, percent = 10},
      {type = "acid", decrease = 12, percent = 10},
      {type = "poison", decrease = 0, percent = 10},
      {type = "laser", decrease = 10, percent = 10}},
	Behemoth_Biter = {
	  {type = "fire", decrease = 0, percent = -25},
      {type = "physical", decrease = 15, percent = 20},
      {type = "impact", decrease = 15, percent = 15},
      {type = "explosion", decrease = 15, percent = 15},
      {type = "acid", decrease = 15, percent = 15},
      {type = "poison", decrease = 0, percent = 15},
      {type = "laser", decrease = 15, percent = 15}},
	Small_Spitter = {
	  {type = "fire", decrease = 0, percent = -45},
      {type = "physical", decrease = 1, percent = 0},
      {type = "impact", decrease = 1, percent = 0},
      {type = "explosion", decrease = 1, percent = 5,},
      {type = "acid", decrease = 1, percent = 0},
      {type = "poison", decrease = 0, percent = 0},
      {type = "laser", decrease = 0, percent = 0}},
	Small_Spitter_Mk2 = {
	  {type = "fire", decrease = 0, percent = -45},
      {type = "physical", decrease = 2, percent = 0},
      {type = "impact", decrease = 2, percent = 0},
      {type = "explosion", decrease = 2, percent = 5,},
      {type = "acid", decrease = 2, percent = 0},
      {type = "poison", decrease = 0, percent = 0},
      {type = "laser", decrease = 0, percent = 0}},
	Small_Spitter_Mk3 = {
	  {type = "fire", decrease = 0, percent = -40},
      {type = "physical", decrease = 3, percent = 0},
      {type = "impact", decrease = 3, percent = 0},
      {type = "explosion", decrease = 3, percent = 5,},
      {type = "acid", decrease = 3, percent = 0},
      {type = "poison", decrease = 0, percent = 0},
      {type = "laser", decrease = 0, percent = 0}},
	Medium_Spitter = {
	  {type = "fire", decrease = 0, percent = -35},
      {type = "physical", decrease = 1, percent = 0},
      {type = "impact", decrease = 5, percent = 5},
      {type = "explosion", decrease = 5, percent = 10},
      {type = "acid", decrease = 5, percent = 5},
      {type = "poison", decrease = 0, percent = 5},
      {type = "laser", decrease = 0, percent = 0}},
	Medium_Spitter_Mk2 = {
	  {type = "fire", decrease = 0, percent = -35},
      {type = "physical", decrease = 2, percent = 0},
      {type = "impact", decrease = 6, percent = 5},
      {type = "explosion", decrease = 6, percent = 10},
      {type = "acid", decrease = 6, percent = 5},
      {type = "poison", decrease = 0, percent = 5},
      {type = "laser", decrease = 0, percent = 5}},
	Medium_Spitter_Mk3 = {
	  {type = "fire", decrease = 0, percent = -30},
      {type = "physical", decrease = 3, percent = 0},
      {type = "impact", decrease = 7, percent = 5},
      {type = "explosion", decrease = 7, percent = 10},
      {type = "acid", decrease = 7, percent = 5},
      {type = "poison", decrease = 0, percent = 5},
      {type = "laser", decrease = 5, percent = 5}},
	Big_Spitter = {
	  {type = "fire", decrease = 0, percent = -25},
      {type = "physical", decrease = 5, percent = 5},
      {type = "impact", decrease = 5, percent = 5},
      {type = "explosion", decrease = 10, percent = 20},
      {type = "acid", decrease = 10, percent = 10},
      {type = "poison", decrease = 0, percent = 10},
      {type = "laser", decrease = 5, percent = 5}},
	Big_Spitter_Mk2 = {
	  {type = "fire", decrease = 0, percent = -25},
      {type = "physical", decrease = 6, percent = 5},
      {type = "impact", decrease = 5, percent = 10},
      {type = "explosion", decrease = 11, percent = 20},
      {type = "acid", decrease = 11, percent = 10},
      {type = "poison", decrease = 0, percent = 10},
      {type = "laser", decrease = 5, percent = 10}},
	Big_Spitter_Mk3 = {
	  {type = "fire", decrease = 0, percent = -25},
      {type = "physical", decrease = 7, percent = 5},
      {type = "impact", decrease = 10, percent = 10},
      {type = "explosion", decrease = 12, percent = 20},
      {type = "acid", decrease = 12, percent = 10},
      {type = "poison", decrease = 0, percent = 10},
      {type = "laser", decrease = 10, percent = 10}},
	Behemoth_Spitter = {
	  {type = "fire", decrease = 0, percent = -25},
      {type = "physical", decrease = 10, percent = 10},
      {type = "impact", decrease = 15, percent = 15},
      {type = "explosion", decrease = 15, percent = 30},
      {type = "acid", decrease = 15, percent = 15},
      {type = "poison", decrease = 0, percent = 15},
      {type = "laser", decrease = 15, percent = 15}},
	Spawner = {
	  {type = "fire", decrease = 0, percent = -25},
      {type = "physical", decrease = 5, percent = 10},
      {type = "impact", decrease = 15, percent = 15},
      {type = "explosion", decrease = 15, percent = 30},
      {type = "acid", decrease = 15, percent = 15},
      {type = "poison", decrease = 0, percent = 15},
      {type = "laser", decrease = 10, percent = 15}},
	Fire = {
      {type = "fire", decrease = 0, percent = 75}},
}